### ISSUE TITLE
crash in client app

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/h5cpp#164]
```gdb
Thread 1 "daquiri" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3dd50bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff3dd6f5d in __GI_abort () at abort.c:90
#2  0x00007ffff3e1f28d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff3f464e8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff3e2664a in malloc_printerr (action=<optimized out>, str=0x7ffff3f42eb0 "malloc(): memory corruption", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5425
#4  0x00007ffff3e2a42d in _int_malloc (av=av@entry=0x7ffff4178c20 <main_arena>, bytes=bytes@entry=792) at malloc.c:3740
#5  0x00007ffff3e2e77b in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3438
#6  0x00007ffff62ffc8a in H5MM_calloc () at /usr/local/hdf5/lib/libhdf5.so.101
#7  0x00007ffff62902a3 in H5FL_arr_malloc () at /usr/local/hdf5/lib/libhdf5.so.101
#8  0x00007ffff63874fd in H5S_set_extent_simple () at /usr/local/hdf5/lib/libhdf5.so.101
#9  0x00007ffff6387a8c in H5Sset_extent_simple () at /usr/local/hdf5/lib/libhdf5.so.101
#10 0x00007ffff67681cb in hdf5::dataspace::Simple::dimensions(std::vector<unsigned long long, std::allocator<unsigned long long> > const&, std::vector<unsigned long long, std::allocator<unsigned long long> > const&) (this=this@entry=0x7fffffffac30, current=std::vector of length 1, capacity 1 = {...}, maximum=std::vector of length 0, capacity 0) at /home/bdv/dev/h5cpp/src/h5cpp/dataspace/simple.cpp:67
#11 0x00007ffff6768333 in hdf5::dataspace::Simple::Simple(std::vector<unsigned long long, std::allocator<unsigned long long> > const&, std::vector<unsigned long long, std::allocator<unsigned long long> > const&) (this=0x7fffffffac30, current=std::vector of length 1, capacity 1 = {...}, maximum=std::vector of length 0, capacity 0) at /home/bdv/dev/h5cpp/src/h5cpp/dataspace/simple.cpp:47
#12 0x0000555555b9b81a in DAQuiri::Dense1D::save(hdf5::node::Group&) const (this=0x5555566fa790, g=...) at /home/bdv/dev/daquiri/source/consumers/dataspaces/dense1d.cpp:94
```

where the invoking line is
```cpp
  auto dspace = hdf5::dataspace::Simple({maxchan_});
```

where ``maxchan_ = 15``

**Comment by eugenwintersberger** [comment]
Is this issue still valid.

**Comment by martukas** [comment]
Looks like I solved this. In turn I have opened #234 , which we can methodically address at some point.
